extends:
  - stylelint-config-standard-scss

ignoreFiles:
  - coverage/**/*
  - docs/style/**/*
  - jsdoc/**/*

rules:
  at-rule-no-unknown:
    - null
  custom-property-pattern:
    - null
  scss/at-rule-no-unknown:
    - true
